### List all employees

GET http://localhost:18085/api/employees
Accept: application/json

### Find employee by id

GET http://localhost:18085/api/employees/5
Accept: application/json


### Create employee

POST http://localhost:18085/api/employees
Content-Type: application/json

{
  "name": "Jane Doe"
}

### Create employee with address

POST http://localhost:18085/api/employees
Content-Type: application/json

{
  "name": "Jane Doe",
  "addresses": [
    {
      "city": "Budapest"
    }
  ]
}

### Update

PUT http://localhost:18085/api/employees/9
Content-Type: application/json

{
  "name": "Jane Doe 2"
}

### Delete

DELETE http://localhost:18085/api/employees/9

### Actuator
GET http://localhost:18085/actuator

### Health

GET http://localhost:18085/actuator/health

### Threaddump
GET http://localhost:18085/actuator/threaddump

### Spring
GET http://localhost:18085/actuator/beans

### Spring
GET http://localhost:18085/actuator/conditions

### Spring
GET http://localhost:18085/actuator/mappings

### Spring
GET http://localhost:18085/actuator/configprops

### HTTP
GET http://localhost:18085/actuator/httptrace

### Liq
GET http://localhost:18085/actuator/info

### Logger
GET http://localhost:18085/actuator/loggers/empapp

### Logger
POST http://localhost:18085/actuator/loggers/empapp
Content-Type: application/json

{
  "configuredLevel": "debug"
}
