FROM eclipse-temurin:17 as builder
WORKDIR app
COPY . .
RUN ./mvnw package

FROM eclipse-temurin:17
WORKDIR app
COPY --from=builder target/*.jar employees.jar
ENTRYPOINT ["java", "-jar", "employee.jar"]